2021-03-13 16:00:50,273 - buildatblog - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: post

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/weicongxie/learnFlask/weicong_blog/buildatblog2020/buildatblog/blueprints/blog.py", line 13, in index
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(per_page=per_page)
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py", line 496, in paginate
    items = self.limit(per_page).offset((page - 1) * per_page).all()
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3373, in all
    return list(self)
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3535, in __iter__
    return self._execute_and_instances(context)
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/orm/query.py", line 3560, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1130, in _execute_clauseelement
    distilled_params,
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1317, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1511, in _handle_dbapi_exception
    sqlalchemy_exception, with_traceback=exc_info[2], from_=e
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/Users/weicongxie/.local/share/virtualenvs/buildatblog2020-ffpmD_YQ/lib/python3.7/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: post
[SQL: SELECT post.id AS post_id, post.title AS post_title, post.body AS post_body, post.timestamp AS post_timestamp 
FROM post ORDER BY post.timestamp DESC
 LIMIT ? OFFSET ?]
[parameters: (10, 0)]
(Background on this error at: http://sqlalche.me/e/13/e3q8)
